const Table = () => {
    return(
        <table
        className="table">
            <thead>
                <th>Фамилия</th>
                <th></th>
                <th></th>

            </thead>
            <tr>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td></td>
            </tr>
        </table>
    )
}
ex